services:
  cuda-hashcat:
    image: hikage/cuda-hashcat-john:latest
    container_name: cuda-hashcat
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all,compute,utility
    ports:
      - "2222:22"
    volumes:
      - /mnt/.ix-apps/app_mounts/cuda-hashcat-john/hashes:/home/cracker/data  # Your ZFS pool
    restart: unless-stopped
x-notes: >
  # cuda-hashcat-john

  **Source** :
  [https://github.com/Elenedeath/cuda-hashcat-john](https://github.com/Elenedeath/cuda-hashcat-john)


  **Image Docker** : hikage/cuda-hashcat-john:latest

  ## Security


  **Read the following security precautions to ensure that you wish to continue
  using this application.**

  ---

  ## Bug Reports and Feature Requests


  If you find a bug in this app or have an idea for a new feature, please file
  an issue at

  https://github.com/Elenedeath/cuda-hashcat-john